<a href="https://colab.research.google.com/github/arthurvteles/AeD_2021/blob/main/Arthur_Teles_ID3_Dataset_Cars_in_India.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Implementação de Árvore de Decisão -- Algoritmo ID3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Implemente uma árvore de decisão ID3 para a predição da variável "NCAP Rating" no dataset
cars-india-dataset. Ela consiste em um score de segurança do veículo: maior o valor, mais seguro é o carro.

Dataset download: https://www.kaggle.com/datasets/vysakhvms/cars-india-dataset

(pode ser necessário registro no Kaggle)

In [ ]:
!unzip archive.zip

unzip:  cannot find or open archive.zip, archive.zip.zip or archive.zip.ZIP.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

cars_df = pd.read_csv("/content/drive/MyDrive/data/Cars India Dataset.csv")
cars_df = cars_df[cars_df['NCAP Rating'] != 'Not Tested']
cars_df = cars_df[cars_df['NCAP Rating'] != 'Not Rated']
train, test = train_test_split(cars_df, test_size=0.2)
train

,Model,Maker,Type,Seats,Displacement,Length,Width,Height,Wheelbase,No_of_Cylinders,...,Rear Brake,Drive,Turning Radius,Fuel Tank Capacity,Boot Space,Fuel Efficiency,Emission Type,Tyre Size,Variants,NCAP Rating
5,Taigun,Volkswagen,Mid Size SUV,5,1498.0,4221,1760,1612,2651,3.0,...,Drum,2WD,5.05,50.0,385.0,18.47,BS VI,205/55 R17,1,5
10,Amaze,Honda,Compact Sedan,5,1498.0,3995,1695,1501,2470,4.0,...,Drum,2WD,4.90,35.0,420.0,24.70,BS VI,175/65 R15,3,4
3,Taigun,Volkswagen,Mid Size SUV,5,999.0,4221,1760,1612,2651,3.0,...,Drum,2WD,5.05,50.0,385.0,19.20,BS VI,205/55 R17,3,5
76,Fortuner,Toyota,SUV,7,2755.0,4795,1855,1835,2745,4.0,...,Disc,4WD,5.80,80.0,296.0,14.20,BS VI,265/60 R18,1,5
90,i20,Hyundai,Hatchback,5,998.0,3995,1775,1505,2580,4.0,...,Drum,2WD,5.20,37.0,326.0,20.25,BS VI,195/55 R16,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,Kiger,Renault,Compact SUV,5,999.0,3991,1750,1605,2500,3.0,...,Drum,2 WD,5.02,40.0,405.0,19.10,BS VI,195/60 R16,5,4
65,XUV 700,Mahindra,SUV,7,2200.0,4695,1890,1755,2750,4.0,...,Disc,AWD,NaN,60.0,NaN,NaN,BS VI,235/60 R18,2,5
32,Triber,Renault,MUV,7,999.0,3991,1739,1643,2636,3.0,...,Drum,2 WD,5.40,40.0,625.0,19.00,BS VI,185/65 R15,4,4
26,Magnite,Nissan,Compact SUV,5,999.0,3994,1758,1572,2500,3.0,...,Drum,2 WD,5.00,40.0,336.0,20.00,BS VI,195/60 R16,5,4
31,Kiger,Renault,Compact SUV,5,999.0,3991,1750,1605,2500,3.0,...,Drum,2 WD,5.02,40.0,405.0,19.00,BS VI,195/60 R16,3,4


#Preenchendo dados com valor NAN com a média das respectivas colunas.

In [ ]:
cars_df['Length'] = pd.to_numeric(cars_df['Length'], downcast = 'float')
test['Length'] = pd.to_numeric(test['Length'], downcast = 'float')

In [ ]:
cars_df['No_of_Cylinders']=cars_df['No_of_Cylinders'].fillna(cars_df['No_of_Cylinders'].mean())
cars_df['Turning Radius']=cars_df['Turning Radius'].fillna(cars_df['Turning Radius'].mean())
cars_df['Fuel Tank Capacity']=cars_df['Fuel Tank Capacity'].fillna(cars_df['Fuel Tank Capacity'].mean())
cars_df['Boot Space']=cars_df['Boot Space'].fillna(cars_df['Boot Space'].mean())
cars_df['Fuel Efficiency']=cars_df['Fuel Efficiency'].fillna(cars_df['Fuel Efficiency'].mean())

In [ ]:
test['No_of_Cylinders']=test['No_of_Cylinders'].fillna(test['No_of_Cylinders'].mean())
test['Turning Radius']=test['Turning Radius'].fillna(test['Turning Radius'].mean())
test['Fuel Tank Capacity']=test['Fuel Tank Capacity'].fillna(test['Fuel Tank Capacity'].mean())
test['Boot Space']=test['Boot Space'].fillna(test['Boot Space'].mean())
test['Fuel Efficiency']=test['Fuel Efficiency'].fillna(test['Fuel Efficiency'].mean())

#Categorizando os valores numéricos.

In [ ]:
test['Length'] = pd.cut(test.Length, bins=np.quantile(test['Length'], [0,0.25,0.5,0.75,1]), labels=['Small', 'Medium', 'Big', ' Enormous'])
test['Width'] = pd.cut(test.Width, bins=np.quantile(test['Width'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'])
test['Height'] = pd.cut(test.Height, bins=np.quantile(test['Height'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'] )
test['Wheelbase'] = pd.cut(test.Wheelbase, bins=np.quantile(test['Wheelbase'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'] )
test.loc[test['No_of_Cylinders'] == 3.0, 'No_of_Cylinders' ]='Three'
test.loc[test['No_of_Cylinders'] == 4.0, 'No_of_Cylinders' ]='Four'
test.loc[test['No_of_Cylinders'] == 5.0, 'No_of_Cylinders' ]='Five'
test.loc[test['No_of_Cylinders'] == 6.0, 'No_of_Cylinders' ]='Six'
test['Turning Radius'] = pd.cut(test['Turning Radius'], bins=np.quantile(test['Turning Radius'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'])
test['Fuel Tank Capacity'] = pd.cut(test['Fuel Tank Capacity'], bins=np.quantile(test['Fuel Tank Capacity'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'])
test['Boot Space'] = pd.cut(test['Boot Space'], bins=np.quantile(test['Boot Space'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'])
test['Fuel Efficiency'] = pd.cut(test['Fuel Efficiency'], bins=np.quantile(test['Fuel Efficiency'], [0,0.25,0.5,0.75,1]), labels=['Good', 'Medium', 'Bad', 'Very Bad'])

test

,Model,Maker,Type,Seats,Displacement,Length,Width,Height,Wheelbase,No_of_Cylinders,...,Rear Brake,Drive,Turning Radius,Fuel Tank Capacity,Boot Space,Fuel Efficiency,Emission Type,Tyre Size,Variants,NCAP Rating
109,Venue,Hyundai,Compact SUV,5,998.0,Medium,Medium,Short,Short,Four,...,Drum,2WD,Short,Medium,Medium,Bad,BS VI,215/60 R16,2,4
79,Fortuner,Toyota,SUV,7,2755.0,Enormous,Large,Enormous,Large,Four,...,Disc,2WD,Enormous,Enormous,Short,Good,BS VI,265/65 R17,1,5
9,Amaze,Honda,Compact Sedan,5,1199.0,Medium,Short,Short,Short,Four,...,Drum,2WD,NaN,Short,Medium,Bad,BS VI,175/65 R15,2,4
141,Carnival,Kia,MPV,9,2199.0,Enormous,Enormous,Large,Enormous,Four,...,Disc,2WD,Enormous,Enormous,Enormous,NaN,BS VI,235/60 R18,1,5
105,Tucson,Hyundai,SUV,5,1997.0,Big,Enormous,Medium,Enormous,Four,...,Disc,2WD,Enormous,Large,Enormous,Good,BS VI,235/60 R18,2,3
13,City 5th Gen,Honda,Sedan,5,1498.0,Big,Short,NaN,Medium,Four,...,Drum,2WD,Medium,Short,Enormous,Very Bad,BS VI,185/55 R16,3,5
33,Triber,Renault,MUV,7,999.0,Small,Short,Medium,Large,Three,...,Drum,2 WD,Large,Short,Enormous,Bad,BS VI,185/65 R15,4,4
135,Seltos,Kia,SUV,5,1353.0,Medium,Medium,Medium,Medium,Four,...,Disc,2WD,Medium,Medium,Large,Medium,BS VI,215/60 R17,2,3
85,Grand i10 Nios,Hyundai,Hatchback,5,1197.0,Small,Short,Short,Short,Four,...,Drum,2WD,Short,Short,Short,Very Bad,BS VI,175/60 R15,3,2
142,Carens,Kia,MUV,6,1353.0,Big,Medium,Large,Enormous,Four,...,Disc,2WD,Short,Medium,NaN,Medium,BS VI,205/65 R16,5,3
155,Safari,Tata,SUV,7,1956.0,Enormous,Enormous,Enormous,Large,Four,...,Disc,2WD,Enormous,Medium,Large,Good,BS VI,235/60 R18,20,6
25,Magnite,Nissan,Compact SUV,5,999.0,Small,Short,Short,Short,Three,...,Drum,2 WD,Short,Short,Medium,Very Bad,BS VI,195/60 R16,5,4
113,Creta,Hyundai,SUV,5,1497.0,Medium,Medium,Medium,Medium,Four,...,Disc,2WD,Medium,Medium,Large,Bad,BS VI,215/60 R17,3,3
147,Carens,Kia,MUV,7,1353.0,Big,Medium,Large,Enormous,Four,...,Disc,2WD,Short,Medium,NaN,Medium,BS VI,205/65 R16,5,3
34,Kwid,Renault,Hatchback,5,799.0,NaN,NaN,Short,NaN,Three,...,Drum,2 WD,Short,NaN,Short,Very Bad,BS VI,155/80 R13,2,2
7,Tiguan,Volkswagen,SUV,5,1984.0,Big,Large,Medium,Large,Four,...,Disc,2WD,Large,Enormous,Enormous,Good,BS VI,235/55 R18,1,5
64,XUV 700,Mahindra,SUV,7,2200.0,Enormous,Enormous,Enormous,Large,Four,...,Disc,2WD,Large,Enormous,Medium,Bad,BS VI,235/60 R18,3,5
69,Thar AX OPT,Mahindra,SUV,4,1997.0,Small,Large,Enormous,Short,Four,...,Drum,4WD,Medium,Enormous,Medium,Good,BS VI,245/75 R16,1,4
152,Safari,Tata,SUV,6,1956.0,Enormous,Enormous,Enormous,Large,Four,...,Disc,2WD,Enormous,Medium,Large,Medium,BS VI,235/60 R18,2,6
67,Thar LX,Mahindra,SUV,4,2184.0,Small,Large,Enormous,Short,Four,...,Drum,4WD,Medium,Enormous,Medium,Good,BS VI,255/65 R18,1,4
115,Creta,Hyundai,SUV,5,1353.0,Medium,Medium,Medium,Medium,Four,...,Disc,2WD,Medium,Medium,Large,Bad,BS VI,215/60 R17,2,3
106,Tucson,Hyundai,SUV,5,1997.0,Big,Enormous,Medium,Enormous,Four,...,Disc,4WD,Enormous,Large,Enormous,Medium,BS VI,235/60 R18,1,3
84,Grand i10 Nios,Hyundai,Hatchback,5,1197.0,Small,Short,Short,Short,Four,...,Drum,2WD,Short,Short,Short,Very Bad,BS VI,175/60 R15,4,2
117,Creta,Hyundai,SUV,5,1493.0,Medium,Medium,Medium,Medium,Four,...,Disc,2WD,Medium,Medium,Large,Very Bad,BS VI,215/60 R17,2,3
143,Carens,Kia,MUV,6,1353.0,Big,Medium,Large,Enormous,Four,...,Disc,2WD,Short,Medium,NaN,Medium,BS VI,205/65 R16,2,3

In [ ]:
cars_df['Length'] = pd.cut(cars_df.Length, bins=np.quantile(cars_df['Length'], [0,0.25,0.5,0.75,1]), labels=['Small', 'Medium', 'Big', ' Enormous'])
cars_df['Width'] = pd.cut(cars_df.Width, bins=np.quantile(cars_df['Width'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'])
cars_df['Height'] = pd.cut(cars_df.Height, bins=np.quantile(cars_df['Height'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'] )
cars_df['Wheelbase'] = pd.cut(cars_df.Wheelbase, bins=np.quantile(cars_df['Wheelbase'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'] )
cars_df.loc[cars_df['No_of_Cylinders'] == 3.0, 'No_of_Cylinders' ]='Three'
cars_df.loc[cars_df['No_of_Cylinders'] == 4.0, 'No_of_Cylinders' ]='Four'
cars_df.loc[cars_df['No_of_Cylinders'] == 5.0, 'No_of_Cylinders' ]='Five'
cars_df.loc[cars_df['No_of_Cylinders'] == 6.0, 'No_of_Cylinders' ]='Six'
cars_df['Turning Radius'] = pd.cut(cars_df['Turning Radius'], bins=np.quantile(cars_df['Turning Radius'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'])
cars_df['Fuel Tank Capacity'] = pd.cut(cars_df['Fuel Tank Capacity'], bins=np.quantile(cars_df['Fuel Tank Capacity'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'])
cars_df['Boot Space'] = pd.cut(cars_df['Boot Space'], bins=np.quantile(cars_df['Boot Space'], [0,0.25,0.5,0.75,1]), labels=['Short', 'Medium', 'Large', 'Enormous'])
cars_df['Fuel Efficiency'] = pd.cut(cars_df['Fuel Efficiency'], bins=np.quantile(cars_df['Fuel Efficiency'], [0,0.25,0.5,0.75,1]), labels=['Good', 'Medium', 'Bad', 'Very Bad'])

In [ ]:
class TreeNode:
  def __init__(self,data):
    self.data = data
    self.children = []
    self.parent = None
    self.is_sheet = False

  def add_child(self, child):
    child.parent = self
    self.children.append(child)

  def print_tree(self):
    pass

Calcula a entropia de uma determinada classe

In [ ]:
def entropy(df,feature_label,feature_value ,target_label ):
  entropy = 0

  if feature_label == target_label:
    dataset_size = df.shape[0]
    tv_count = df[target_label].value_counts()[feature_value]
    probability = tv_count/dataset_size
    entropy_tv = - probability * np.log2(probability)
    entropy += entropy_tv
    return entropy


  new_dataset = df.loc[(df[feature_label] == feature_value)]
  new_dataset = new_dataset[[feature_label, target_label]]
  new_dataset_size = new_dataset[feature_label].count()
  target_value = new_dataset[target_label].unique()


  for tv in target_value:
    tv_count = new_dataset[target_label].value_counts()[tv]
    probability = tv_count/new_dataset_size
    entropy_tv = - probability * np.log2(probability)
    entropy += entropy_tv

  return entropy

Calcula o ganho de informação

In [ ]:
def info_gain(df, feature_label, target_label, total_entropy):
  feature_label_values = df[feature_label].unique()
  df_size = df.shape[0]
  gain = 0.0

  for flv in feature_label_values:
    feature_entropy = entropy(df,feature_label, flv, target_label)
    feature_count = df[df[feature_label] == flv].shape[0]
    feature_probability = feature_count/df_size
    gain += feature_probability * feature_entropy

  return total_entropy - gain

In [ ]:
#calcular a entropia total
target_values = test['NCAP Rating'].unique()
total_entropy = 0

for tv in target_values:
  tv_entropy = entropy(test,'NCAP Rating', tv, 'NCAP Rating')
  total_entropy += tv_entropy

2.1477110700184037

Finding the most informative feature

In [ ]:
def finding_the_most_informative(df, target_label, total_entropy):
  most_informative = {}
  features = df.columns.drop(target_label)

  for ft in features:
    feature_gain = info_gain(df,ft,target_label,total_entropy)
    new_data = {ft:feature_gain}
    most_informative.update(new_data)

  most_informative = sorted(most_informative.items(), key= lambda x:x[1], reverse = True )
  return most_informative

print(finding_the_most_informative(test,'NCAP Rating', total_entropy))

[('Model', 2.1477110700184037), ('Engine Type', 2.1477110700184037), ('Displacement', 2.037515569931865), ('Tyre Size', 1.7673200698453262), ('Maker', 1.317515569931865), ('Boot Space', 1.291314688649721), ('Length', 1.2710651915826583), ('Wheelbase', 1.2554508105601307), ('Transmission', 1.2229344508678537), ('Fuel Tank Capacity', 1.1144127099799719), ('Width', 1.0831839479349168), ('Type', 1.0642644169311906), ('Height', 1.0579065701049424), ('Rear Brake', 0.8265649754771962), ('Turning Radius', 0.7714561917557361), ('Variants', 0.7705326883035664), ('Fuel Efficiency', 0.7509236884766437), ('Seats', 0.6017931949482891), ('Drive', 0.36328077860567354), ('Fuel', 0.26190118890933745), ('No_of_Cylinders', 0.19877436502774803), ('Front Brake', 0.0), ('Emission Type', 0.0)]

In [ ]:
test.to_csv('cars_india.csv', encoding='utf-8')